---

- name: "Install Docker deps"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: "Add Docker apt key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "Add Docker apt repository"
  apt_repository:
    repo: >
      deb [arch=amd64]
      https://download.docker.com/linux/ubuntu
      bionic stable

- name: "Install Docker"
  apt:
    name: docker-ce
    update_cache: yes
    state: present
