---

# Package notes:
# autoconf is needed for `pip install jq` to work
# python-rados enables ceph's python imports. Can't use pip for it.
- name: "Install Apt packages"
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: present
  with_items:
    - autoconf
    - git
    - python3
    - python3-pip
    - python3-venv
    - python3-setuptools
    - tmux
    - vim
    - python-rados

- name: "Update pip"
  pip:
    executable: pip3
    state: latest
    name: "pip"
  register: update_pip

# jsc2f:  A tool I made, it lets you edit json cells from SQL as files
# httpie: a nice http API testing cli
# jq:     parses json into a nice format for bash scripting and easy reading
#         ... Removed for now, the installer is broken :-(
# ansible: it automation tool. Required openstacksdk to run OpenStack plays
# python-openstackclient: Installs the OpenStack CLI
- name: "Install python3 workstation apps"
  pip:
    executable: pip3
    name: "{{ item }}"
    state: present
  with_items:
    - virtualenv
    - jsc2f
    - httpie
    - ansible
    - openstacksdk
    - breqwatr-deployment-tool
    - python-openstackclient
    - awscli
    - tox
