---
- include: hostname.yml
- include: general-packages.yml
- include: docker.yml
- include: vim-setup.yml
- include: tmux-setup.yml
- include: google-sdk.yml
# Anything that needs NPM must be included below nodejs.yml
- include: nodejs.yml
