---

- name: "create vim directories"
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
  with_items:
    - "{{ home_dir }}/.vim/autoload"
    - "{{ home_dir }}/.vim/spell"

- name: "Get vim-plug"
  uri:
    dest: "{{ home_dir }}/.vim/autoload/plug.vim"
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    owner: "{{ username }}"
    group: "{{ username }}"

- name: "Deploy vimrc file"
  template:
    src: vimrc
    dest: "{{ home_dir }}/.vimrc"
    owner: "{{ username }}"
    group: "{{ username }}"
  register: vimrc_file

- name: "Install plugins"
  shell: >
    vim -E -s
    -c 'source {{ home_dir }}/.vimrc'
    -c PlugInstall
    -c qa
    || true
  when: vimrc_file.changed
  failed_when: False

- name: "Install vim python dependency apps"
  pip:
    executable: pip3
    name: "{{ item }}"
    state: present
  with_items:
    - pylint
    - flake8

- name: "Deploy VIM spellcheck dictionary additions"
  template:
    src: en.utf-8.add
    dest: "{{ home_dir }}/.vim/spell/en.utf-8.add"
