" syntax highlighting
syntax on

" Maintain undo history between sessions
" " don't forget to run mkdir ~/.vim/undodir
set undofile
set undodir=~/.vim/undodir
" " fix undo in vi mode
set nocompatible

" tab settings
set tabstop=2 shiftwidth=2 expandtab
autocmd FileType python setlocal shiftwidth=4 tabstop=4 expandtab
autocmd FileType javascript setlocal shiftwidth=2 tabstop=2 expandtab
autocmd FileType html setlocal shiftwidth=2 tabstop=2 expandtab

" enable auto indentation
set autoindent

" disable word wrap
set nowrap

" line length ruler at 80 chars (mostly for pep8)
set colorcolumn=80
highlight colorcolumn ctermbg=darkyellow ctermfg=black

" Make trailing whitespace show up as bright red
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/

" easier controls to directionally switch between vim panes like we do in tmux
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

" use dark background theme
set bg=dark


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"
" Plugins - Managed by Vim-Plug
" " To install the plugins configured below, open vim and run:
" " :PlugInstall

" Specify plugins directory
" " - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')

" Fugitive: Git wrapper to make merge conflicts easier to resolve
Plug 'tpope/vim-fugitive'

" ALE: Asynchronous Lint Engine. (Requires Vim8)
let g:ale_lint_on_text_changed = 'normal'
let g:ale_lint_on_enter = 1
let g:ale_completion_enabled = 1
" For python to work, run this outside a venv. Requires python-pip.
" " pip install pylint
" " pip install flake8
" For javascript to work, run this. Requires NPM be installed.
" " npm install -g jshint
" " 'javascript': ['jshint']
" For CSS files to work, run this. Requires NPM be installed
" " npm install -g stylelint
" " 'css': ['stylelint']
let g:ale_linters = {'python': ['flake8', 'pylint'],}
Plug 'w0rp/ale'


" Initialize plugin system
call plug#end()
